<template>
    <div class="container1">
      <div class="adjust">
        <h2 class="Name">Sample Report</h2>
        <hr class="horizontal-line" />
        <h3 class="medical-receipt-heading">Neurological Diagnosis based on EEG File</h3>

    </div>
      <div class="container">
        <div class="section diagnosis">
          <p class="section-title">Diagnosis</p>
          <p>
            The EEG recording analysis reveals
            <i
            ><span style="color: red">
                irregular spikes in delta and theta waveforms, predominantly
                localized in the temporal regions bilaterally.</span
              ></i
              >
            These patterns suggest abnormal neuronal activity, potentially
            indicating epileptiform activity. The observed EEG abnormalities
            align with reported symptoms of focal seizures and altered
            consciousness, indicative of a possible epilepsy diagnosis.
          </p>
        </div>
        <div class="section recommendation">
            <p class="section-title">Recommendation</p>
            Given the identified epileptiform activity in the EEG readings and the
            associated clinical symptoms, an immediate consultation with a
            neurologist specializing in epileptic conditions is strongly advised.
            Further diagnostic evaluations, such as MRI imaging and extended
            ambulatory EEG monitoring, are recommended for accurate diagnosis and
            localization of seizure foci. <i>Initiation of antiepileptic drug therapy
          tailored to suppress abnormal brain activity is essential for
          effective seizure management.</i>
        </div>
        <div class="section medicines-left">
            <p class="section-title">Medicication</p>
          The prescribed treatment plan includes: <br />
          <strong>Antiepileptic Drugs:</strong> Initiation of medication regimen
          based on neurologist's assessment and diagnosis. <br/>
          <strong>Additional Interventions:</strong> Consideration of potential
          interventions guided by diagnostic results.
        </div>
        <div class="section medicines-right">
          Please note that this is a simulated EEG analysis report generated by
          AI. Actual diagnostic and treatment decisions should be made by
          qualified healthcare professionals based on individual patient
          assessments and test results.
        </div>
      </div>
      <hr class="horizontal-line" />
      <p class="return-info">There is a cure for every disease except death</p>
    </div>
</body>
</template>

<style scoped>
      body {
        font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
        margin: 20px;
      }

      .container1 {
        max-width: 800px;
        margin: 0 auto;
      }

      .contact-info {
        font-size: 12px;
        text-align: center;
      }

      .horizontal-line {
        border-top: 2px solid black;
        margin: 20px 0;
      }

      .medical-receipt-heading {
        text-align: center;
        font-weight: bold;
        font-size: 22px;
        margin-bottom: 20px;
      }

      .info {
        display: flex;
        grid-template-columns: 1fr 1fr;
        justify-content: space-between;
        margin-bottom: 20px;
      }

      .info div {
        flex: 0 0 48%;
      }
      .container {
        max-width: 1500px;
        margin: 0 auto;
        display: grid;
        grid-template-columns: auto auto; /* Split into two columns */
        grid-template-rows: auto auto; /* Define two rows */
        gap: 20px; /* Gap between sections */
      }

      .section {
        border: 1px solid #ccc;
        padding: 10px;
      }

      .diagnosis,
      .recommendation,
      .medicines-left,
      .medicines-right {
        border: none;
        grid-column: span 1; /* Each section spans one column */
      }
      .medicines-right {
        text-align: left;
      }

      .diagnosis {
        grid-row: 1 / 2; /* Diagnoses on top left */
      }

      .recommendation {
        grid-row: 1 / 2; /* Recommendation on top right */
        justify-self: end; /* Align to end (right) */
      }

      .medicines-left {
        grid-row: 2 / 3; /* Medicines on bottom left */
      }

      .medicines-right {
        grid-row: 2 / 3; /* Medicines on bottom right */
        justify-self: end; /* Align horizontally to the right */
        font-style: italic;
        text-align: right;
        display: flex;
        align-items: flex-end; /* Align content to the bottom */
      }

      .section-title {
        font-weight: bold;
        font-size: larger;
        margin-bottom: 8px;
      }

      .horizontal-line {
        border-top: 2px solid black;
        margin: 20px 0;
      }
      .return-info {
        font-size: 12px;
        font-style: italic;
        text-align: center;
        font-size: medium;
        margin-top: 20px;
      }

      .Name {
        text-align: center;
      }

      .adjust {
        font-size: 14px;
      }
    </style>